test merge
thu-hien-qt/web_film pull request #2
Opened 2024-07-12 03:24 UTC by thu-hien-qt

test pull request

2024-07-12 03:25 UTC, thu-hien-qt commented
dsdsa

2024-07-17 02:35 UTC, ngan-le-lm requested changes

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +            $genre = new Genre;
Các objects genre, director, actor chỉ có name, không có đủ các thông tin khác!
Cách sửa : trong GenreRepository, PersonRepository viết thêm các hàm getByFilm($film), getActorsByFilm($film), các hàm này trả về danh sách các genres / actors theo film

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +            $films[] = $film;
thêm genres, actors như trong hàm getByFilmId()

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Model/film.php
> +        return $genres;
sao không `return $this->genres` ?

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Model/film.php
> +        return $actors;
sao không return $this->actors ?

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +    public function getByFilm(Film $film)
hàm này không có ý nghĩa

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +        $sql = "SELECT filmID FROM film WHERE title = :title";
có thể có nhiều phim cùng title, không được select theo title !
để lấy id của phim vừa được insert, dùng hàm getLastInsertId của PDOStatement

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/PersonRepository.php
> +    public function getActor()
getActor**s**

2024-07-17 02:35 UTC, ngan-le-lm commented on include/Repository/PersonRepository.php
> +    public function getDirector()
số nhiều

2024-07-17 02:35 UTC, ngan-le-lm commented on admin/add_movie.php
> +        OR empty($_POST["actors"]) OR empty($_POST["genres"])
phải dùng || thay vì OR

2024-07-24 02:58 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +    public function Insert(Film $film)
tên hàm phải bắt đầu bằng chữ viết thường (insert)

2024-07-24 02:58 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +    public function Delete(Film $film)
tên hàm phải bắt đầu bằng chữ viết thường

2024-07-24 02:58 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +    public function Update(Film $film)
tên hàm phải bắt đầu bằng chữ viết thường

2024-07-24 02:58 UTC, ngan-le-lm commented on manage/add.php
> +    if ($id == 2 && isset($_POST['Psubmit']) && isset($_POST['name']) && isset($_POST['gender']) && isset($_POST['birthday']) && isset($_POST['role'])) {
- 1 file chỉ làm 1 việc, không nên vừa add person, vừa add genre
- không dùng từ viết tắt Psubmit ? Gsubmit
- sửa tên file lại cho rõ

2024-07-24 02:58 UTC, ngan-le-lm commented on include/Model/film.php
> +<?php
đổi tên file, viết hoa chữ đầu

2024-07-24 02:58 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +class FilmRespository
sai chính tả : FilmRespository

2024-07-29 02:36 UTC, ngan-le-lm commented on include/Repository/FilmRepository.php
> +            $genre = new Genre;
tránh lặp lại đoạn code thêm các actors, director, genre liên kết tới film bằng cách viết hàm populateFilm()

2024-07-31 02:43 UTC, ngan-le-lm approved these changes

2024-07-31 02:44 UTC, merged